### ISSUE TITLE
pip install limmbo error

### ISSUE THREAD

**Issue by em812** [HannahVMeyer/limmbo#7]
I installed LIMIX from conda-forge as suggested without problems. Then I tried to install LiMMBo with 'pip install limmbo' and I am getting the following error:

 ERROR: Command errored out with exit status 1:
     command: /anaconda3/envs/limmbo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r_/lkbpdf5x5295kp3nxtrkd5d40000gp/T/pip-install-yuj5yxl2/pp/setup.py'"'"'; __file__='"'"'/private/var/folders/r_/lkbpdf5x5295kp3nxtrkd5d40000gp/T/pip-install-yuj5yxl2/pp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/r_/lkbpdf5x5295kp3nxtrkd5d40000gp/T/pip-install-yuj5yxl2/pp/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r_/lkbpdf5x5295kp3nxtrkd5d40000gp/T/pip-install-yuj5yxl2/pp/setup.py", line 12, in <module>
        from pp import version as VERSION
      File "/private/var/folders/r_/lkbpdf5x5295kp3nxtrkd5d40000gp/T/pip-install-yuj5yxl2/pp/pp.py", line 121
        print sout,
                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(sout, end=" ")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by HannahVMeyer** [comment]
Hi,
could you provide more information about your setup please?
Which python version, which limmbo version and which limix version are you using?

We are working on a new release of limmbo, that includes more features, speed up and improved documentation. It will also include an update to the latest limix version which has had a major make over. 

I am tagging @horta : Danilo, could you point us to the multi-variate variance decomposition module in the latest limix release? Clearly, the limix.mtset module is no longer available.

Thanks,

Hannah

**Comment by horta** [comment]
Hi Hannah,

Limix v3 still doesnt have that unfortunately. It will be back on 3.1.0 but it will probably take weeks to be released, as
the command line interface for struct-lmm (and qtl in general) is top in the priorities).

However, a working version of variance-decomposition is on the develop branch (which will release limix 3.1.0 eventually):

- Implementation: https://github.com/limix/limix/blob/develop/limix/vardec/_vardec.py
- Usage example: https://github.com/limix/limix/blob/develop/limix/vardec/test/test_vardec.py#L134

You can install it via

pip install git+https://github.com/limix/limix.git@develop

The successful installation is not guaranteed but I can help with that...

Best,
Danilo

**Comment by horta** [comment]
Also, we don't support python v2 any longer. It is quite outdated and many packages we depend on are not supporting it anymore

**Comment by HannahVMeyer** [comment]
> Also, we don't support python v2 any longer. It is quite outdated and many packages we depend on are not supporting it anymore

We have switched the python 3 as well.

**Comment by HannahVMeyer** [comment]
> Hi Hannah,
> 
> Limix v3 still doesnt have that unfortunately. It will be back on 3.1.0 but it will probably take weeks to be released, as
> the command line interface for struct-lmm (and qtl in general) is top in the priorities).
> 
> However, a working version of variance-decomposition is on the develop branch (which will release limix 3.1.0 eventually):
> 
> * Implementation: https://github.com/limix/limix/blob/develop/limix/vardec/_vardec.py
> * Usage example: https://github.com/limix/limix/blob/develop/limix/vardec/test/test_vardec.py#L134
> 
> You can install it via
> 
> pip install git+https://github.com/limix/limix.git@develop
> 
> The successful installation is not guaranteed but I can help with that...
> 
> Best,
> Danilo

Thanks for getting back to us. The implementation for initiation the variance decomposition has completely changed , how about the implementation of the actual estimation of the variance components? 

For instance line 195 does a normalisation of the provided relatedness matrix, what if it was normalised before? Will there be an option to supply eigenvectors and values of the kinship matrix?

Thank you very much for your help,
Hannah

**Comment by horta** [comment]
I've decided to always normalize the matrices because the variance comparison only makes sense when the matrices are on the same scale. And I perform only a scaling normalization, which won't affect the structure of the matrices. It is a harmless normalization, lets say.

About providing an eigendecomposition, yes, I want to implement that. In fact, I want to have that implemented in every function that receives a square matrix: the user would be able to provide either a decomposition or the matrix itself.

Thanks for reminding me of those things...
